feat: animated emojis
vednoc/dark-whatsapp pull request #180
Opened 2020-09-19 16:37 UTC by E-RELevant

Like the mobile app, animates the heart emoji when displayed as a single emoji, w/o additional text (64px).
In addition, animates the red-suit & kiss emojis.

2020-09-19 17:28 UTC, vednoc requested changes
This should be it.

I replaced comments with the actual emoji codes so that we can minimize the confusion.

Also, what do you think of adding "☺️" to `heartPulse` animation? ☺️

2020-09-19 17:28 UTC, vednoc commented on wa.user.styl
> +                }
Can be refactored as:
```styl
                img[src$='-64.png'] {
                    /// ♥️, ❤️ 
                    &[alt='♥️'], &[alt='❤️'] { animation: heartPulse 1s infinite }
                    /// 💋
                    &[alt='💋'] { animation: kiss 1s infinite }
                }

```

2020-09-19 17:28 UTC, vednoc commented on wa.user.styl
> +          80%  { transform: scale(1) rotate(-30deg)  }
There's one extra space at the end on both of these lines. 😄

2020-09-19 20:34 UTC, merged

2020-09-19 20:36 UTC, E-RELevant commented
Thought about making it to the 😍 emoji, do you think ☺️ should be used instead?

2020-09-27 21:12 UTC, vednoc commented
I've added 🤩, 😍 , ❣️ , and ☺️ to the list. No clue how to un-merge the PR without getting that ugly "revert" commit, but at least we have a reference to ddf4cd8. 🎉